### ISSUE TITLE
Extracting the detected text-lines

### ISSUE THREAD

**Issue by deepseek** [GA-17a/PSENet#1]
@GA-17a 
Can you add a script that would extract the [detected lines](https://github.com/GA-17a/PSENet/blob/master/detection_result/taxi/res_taxi_gs_48_xiaomi6x_28.txt) into cropped images.
This will be very helpful, so that we can latter-on use an OCR to recognize the cropped lines.

Waiting for your reply

**Comment by GA-17a** [comment]
> @GA-17a
> Can you add a script that would extract the [detected lines](https://github.com/GA-17a/PSENet/blob/master/detection_result/taxi/res_taxi_gs_48_xiaomi6x_28.txt) into cropped images.
> This will be very helpful, so that we can latter-on use an OCR to recognize the cropped lines.
> 
> Waiting for your reply
You can implement this function by Python easily.

**Comment by GA-17a** [comment]
You can implement this function by Python easily.
